version: '3.7'
services:

  cargo:
    image: harrisonai/rust:1.60-0.2
    entrypoint: cargo
    volumes:
      - '~/.cargo/registry:/usr/local/cargo/registry'
      - '.:/app'
    working_dir: '/app'
